routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PublicController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CertificationController;
use App\Http\Controllers\EstablishmentController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\FormsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PublicController::class,'index'])->name('public');
Route::post('/sendmail', [PublicController::class,'sendmail'])->name('sendmail');
Route::get('/cron', [PublicController::class,'cron'])->name('cron');

Route::get('/dashboard', function () {
    return view('neon');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/settings', [HomeController::class, 'settings'])->name('settings');
Route::patch('/settings/update', [HomeController::class, 'settings_update'])->name('settings_update');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('certifications', CertificationController::class);
    Route::resource('establishments', EstablishmentController::class);
    Route::resource('events', EventController::class);
    Route::resource('forms', FormsController::class);
});

app/Http/Controllers/FormsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Establishment;
use Illuminate\Support\Str;
use App\Models\Form;
use Auth;

class FormsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('auth');
        $this->middleware('permission:form-list|form-create|form-edit|form-delete', ['only' => ['index','show']]);
        $this->middleware('permission:form-create', ['only' => ['create','store']]);
        $this->middleware('permission:form-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:form-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $forms = Form::latest()->paginate(20);

        return view('form.index',compact('forms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('form.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'fields' => 'required',
        ]);

        $form = new Form;
        $form->name = $request->input('name');
        $form->slug = Str::of($request->input('name'))->slug('-');
        $form->fields = json_encode( $request->input('fields') );
        $form->save();

        return redirect()->route('forms.index')
            ->with('success','Form successfully created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Form $form)
    {
        $id = $request->input('es');
        $establishment = Establishment::find($id);

        if (!$establishment) {
            return redirect('establishments');
        }

        $right = null;
        $left = null;
        $fields = null;

        if ( $form->fields ) 
        {
            $fields = json_decode($form->fields);

            $right = $fields->right;
            $left = $fields->left;

            if (count($left)) 
            {   
                $newLeft = [];
                foreach ( $left as $l ) 
                {
                    $l = json_decode($l);
                    $l->slug = Str::slug($l->name, '_');
                    $newLeft[] = $l;
                }

                $left = $newLeft;
            }   

            if (count($right)) 
            {

                $newRight = [];
                foreach ( $right as $r ) 
                {
                    $r = json_decode($r);
                    $r->slug = Str::slug($r->name, '_');
                    $newRight[] = $r;
                }

                $right = $newRight;
            }
        }

        if ( $form->view ) {

            return view($form->view,compact('form','establishment','left','right','fields'));

        } else {

            return view('form.input',compact('form','establishment','left','right','fields'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Form $form)
    {
        $right = null;
        $left = null;
        $fields = null;

        if ( $form->fields ) 
        {
            $fields = json_decode($form->fields);

            $right = $fields->right;
            $left = $fields->left;

            if ( count($left) )
            {
                $newLeft = [];
                foreach ( $left as $l ) 
                {
                    $l = json_decode($l);
                    $l->slug = Str::slug($l->name, '_');
                    $newLeft[] = $l;
                }

                $left = $newLeft;
            }

            if ( count($right) )
            {
                $newRight = [];
                foreach ( $right as $r ) 
                {
                    $r = json_decode($r);
                    $r->slug = Str::slug($r->name, '_');
                    $newRight[] = $r;
                }

                $right = $newRight;
            }
        }

        return view('form.edit',compact('form','left','right','fields'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'fields' => 'required',
        ]);

        $form = Form::find($id);
        $form->name = $request->input('name');
        $form->slug = Str::of($request->input('name'))->slug('-');
        $form->fields = json_encode( $request->input('fields') );
        $form->save();

        return redirect()->route('forms.edit',$id)
            ->with('success','Form successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Form $form)
    {
        $form->delete();
        return redirect('forms')->with('success','Form successfully removed.');
    }
}

resources/views/forms/edit/business.blade.php
@extends('neon')

@section('title')
<h2>Business Occupancy Checklist</h2>
@endsection

@section('action')
    <a class="btn btn-default" href="javascript:;" onclick="window.history.back();">Go Back</a>
@endsection

@section('content')
    
    <hr>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('certifications.store') }}" method="POST">
        @csrf
         
            {{-- 
        <div class="col-xs-12 col-sm-12 col-md-12">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div> --}}
    


    </form>

@endsection

resources/views/forms/edit/fire-safety.blade.php
@extends('neon')

@section('title')
<h2>{{ $establishment->name }}</h2>
@endsection

@section('action')
    <a class="btn btn-primary icon-left btn-icon" href="javascript:;" onclick="window.history.back();">
        Go Back <i class="entypo-left-open"></i>
    </a>
@endsection

@section('content')
    
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('certifications.update',$certification->id) }}" method="POST">
        @csrf
        @method('PUT')
        <input type="hidden" name="name" value="{{ $form->name }}">
        <input type="hidden" name="form_id" value="{{ $form->id }}">
        <input type="hidden" name="establishment_id" value="{{ $establishment->id }}">
        
        <div class="row">
            <div class="col-md-3">
                 <div class="panel panel-default panel-shadow" data-collapsed="0"><!-- to apply shadow add class "panel-shadow" -->
                    
                    <!-- panel head -->
                    <div class="panel-heading">
                        <div class="panel-title">Establishment Details</div>
                    </div>

                    <!-- panel body -->
                    <div class="panel-body">
                        <table class="table">
                            <tr><td><b>Name:</b></td> <td>{{ $establishment->name }}</td></tr>
                            <tr><td><b>Nature of Business:</b></td> <td>{{ $establishment->description }}</td></tr>
                            <tr><td><b>Address:</b></td> <td>{{ $establishment->address }}</td></tr>
                            <tr><td><b>Owner:</b></td> <td>{{ $establishment->owner_name }}</td></tr>
                            <tr><td><b>Phone:</b></td> <td>{{ $establishment->phone }}</td></tr>
                            <tr><td><b>Email:</b></td> <td>{{ $establishment->email }}</td></tr>    
                        </table>

                    </div>
                </div>

                @can('certification-delete')
                    <div class="panel panel-default panel-shadow" data-collapsed="0">
                        <div class="panel-heading">
                            <div class="panel-title">Validity</div>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                <strong>Valid From:</strong>
                                <input type="date" name="valid_from" value="{{ $certification->valid_from }}" class="form-control" placeholder="MM/DD/YYYY">
                            </div>
                            <div class="form-group">
                                <strong>Valid Until:</strong>
                                <input type="date" name="valid_until" value="{{ $certification->valid_until }}" class="form-control" placeholder="MM/DD/YYYY">
                            </div>
                            <div class="form-group">
                                <strong>Status:</strong>
                                <select name="status" class="form-control">
                                    <option value="pending"{{ $certification->status == 'pending' ? ' selected':'' }}>Pending</option>
                                    <option value="approved"{{ $certification->status == 'approved' ? ' selected':'' }}>Approved</option>
                                    <option value="expired"{{ $certification->status == 'expired' ? ' selected':'' }}>Expired</option>
                                </select>
                            </div>

                            <button type="submit" class="btn btn-success btn-icon">Update <i class="entypo-check"></i></button>
                        </div>
                    </div>
                @endcan
                
            </div>
            <div class="col-md-9">
                
                <div class="panel panel-default panel-shadow" data-collapsed="0"><!-- to apply shadow add class "panel-shadow" -->
                    
                    <!-- panel head -->
                    <div class="panel-heading">
                        <div class="panel-title">Fire Safety Inspection Certificate Form</div>
                    </div>

                    <!-- panel body -->
                    <div class="panel-body">
                        <h3 style="margin:0;">Fire Safety Inspection Certificate</h3>
                        <hr>
                         <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Name of Establishment:</strong>
                                    <input type="text" name="contents[name]" value="{{ $data->name }}" class="form-control" placeholder="">
                                </div>
                                <div class="form-group">
                                    <strong>Name of Owner/Representative:</strong>
                                    <input type="text" name="contents[owner_name]" value="{{ $data->owner_name }}" class="form-control" placeholder="">
                                </div>
                                <div class="form-group">
                                    <strong>Purpose:</strong>
                                    <select name="contents[purpose]" class="form-control">
                                        <option value="For Business Permit (NEW/RENEWAL)"{{ $data->purpose == 'For Business Permit (NEW/RENEWAL)' ? ' selected':'' }}>For business permit (NEW/RENEWAL)</option>
                                        <option value="Certificate of Annual Inspection (PEZA)"{{ $data->purpose == 'Certificate of Annual Inspection (PEZA)' ? ' selected':'' }}>Certificate of Annual Inspection (PEZA)</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <strong>Address:</strong>
                                    <input type="text" name="contents[address]" value="{{ $data->address }}" class="form-control" placeholder="Janiuay Public Market, Janiuay, Iloilo City">
                                </div>
                                <div class="form-group">
                                    <strong>FSIC Number:</strong>
                                    <input type="text" name="contents[fsic_number]" value="{{ $data->fsic_number }}" class="form-control" placeholder="FSIC Number">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                
                                <div class="form-group">
                                    <strong>Amount Paid:</strong>
                                    <input type="text" name="contents[amount_paid]" value="{{ $data->amount_paid }}" class="form-control" placeholder="0.00">
                                </div>
                                <div class="form-group">
                                    <strong>Reciept Number:</strong>
                                    <input type="text" name="contents[reciept_number]" value="{{ $data->reciept_number }}" class="form-control" placeholder="">
                                </div>
                                <div class="form-group">
                                    <strong>Payment Date:</strong>
                                    <input type="date" name="contents[date_paid]" value="{{ $data->date_paid }}" class="form-control" placeholder="MM/DD/YYYY">
                                </div>
                                
                            </div>
                            
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <button type="submit" class="btn btn-primary btn-icon">Submit <i class="entypo-check"></i></button>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/forms/edit/healthcare.blade.php
@extends('neon')

@section('title')
<h2>Healthcare Occupancy Checklist</h2>
@endsection

@section('action')
    <a class="btn btn-default" href="{{ route('certifications.index') }}">Go Back</a>
@endsection

@section('content')
    
    <hr>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('certifications.store') }}" method="POST">
    	@csrf
         
            {{-- 
	    <div class="col-xs-12 col-sm-12 col-md-12">
            <button type="submit" class="btn btn-primary">Submit</button>
	    </div> --}}
	


    </form>

@endsection

resources/views/forms/edit/industrial.blade.php
@extends('neon')

@section('title')
<h2>Industrial Occupancy Checklist</h2>
@endsection

@section('action')
    <a class="btn btn-default" href="{{ route('certifications.index') }}">Go Back</a>
@endsection

@section('content')
    
    <hr>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('certifications.store') }}" method="POST">
        @csrf
         
            {{-- 
        <div class="col-xs-12 col-sm-12 col-md-12">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div> --}}
    


    </form>

@endsection

resources/views/forms/edit/mercantile.blade.php
@extends('neon')

@section('title')
<h2>Mercantile Occupancy Checklist</h2>
@endsection

@section('action')
    <a class="btn btn-default" href="{{ route('certifications.index') }}">Go Back</a>
@endsection

@section('content')
    
    <hr>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('certifications.store') }}" method="POST">
        @csrf
         
            {{-- 
        <div class="col-xs-12 col-sm-12 col-md-12">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div> --}}
    


    </form>

@endsection

resources/views/forms/edit/miscelanious.blade.php
@extends('neon')

@section('title')
<h2>Miscelanious Occupancy Checklist</h2>
@endsection

@section('action')
    <a class="btn btn-default" href="{{ route('certifications.index') }}">Go Back</a>
@endsection

@section('content')
    
    <hr>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('certifications.store') }}" method="POST">
    	@csrf
         
            {{-- 
	    <div class="col-xs-12 col-sm-12 col-md-12">
            <button type="submit" class="btn btn-primary">Submit</button>
	    </div> --}}
	


    </form>

@endsection

resources/views/forms/edit/places-of-assembly.blade.php
@extends('neon')

@section('title')
<h2>Places of Assembly Occupancy Checklist</h2>
@endsection

@section('action')
    <a class="btn btn-default" href="{{ route('certifications.index') }}">Go Back</a>
@endsection

@section('content')
    
    <hr>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('certifications.store') }}" method="POST">
        @csrf
         
            {{-- 
        <div class="col-xs-12 col-sm-12 col-md-12">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div> --}}
    


    </form>

@endsection

resources/views/forms/edit/residential.blade.php
@extends('neon')

@section('title')
<h2>Residential Occupancy Checklist</h2>
@endsection

@section('action')
    <a class="btn btn-default" href="{{ route('certifications.index') }}">Go Back</a>
@endsection

@section('content')
    
    <hr>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('certifications.store') }}" method="POST">
        @csrf
         
            {{-- 
        <div class="col-xs-12 col-sm-12 col-md-12">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div> --}}
    


    </form>

@endsection

resources/views/forms/edit/small-general.blade.php
@extends('neon')

@section('title')
<h2>Small/General Business Establishment Checklist</h2>
@endsection

@section('action')
    <a class="btn btn-default" href="{{ route('certifications.index') }}">Go Back</a>
@endsection

@section('content')
    
    <hr>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('certifications.store') }}" method="POST">
        @csrf
         
            {{-- 
        <div class="col-xs-12 col-sm-12 col-md-12">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div> --}}
    


    </form>

@endsection

resources/views/forms/edit/storage.blade.php
@extends('neon')

@section('title')
<h2>Storage Occupancy Checklist</h2>
@endsection

@section('action')
    <a class="btn btn-default" href="{{ route('certifications.index') }}">Go Back</a>
@endsection

@section('content')
    
    <hr>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('certifications.store') }}" method="POST">
        @csrf
         
            {{-- 
        <div class="col-xs-12 col-sm-12 col-md-12">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div> --}}
    


    </form>

@endsection