routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PublicController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CertificationController;
use App\Http\Controllers\EstablishmentController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\FormsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PublicController::class,'index'])->name('public');
Route::post('/sendmail', [PublicController::class,'sendmail'])->name('sendmail');
Route::get('/cron', [PublicController::class,'cron'])->name('cron');

Route::get('/dashboard', function () {
    return view('neon');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/settings', [HomeController::class, 'settings'])->name('settings');
Route::patch('/settings/update', [HomeController::class, 'settings_update'])->name('settings_update');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('certifications', CertificationController::class);
    Route::resource('establishments', EstablishmentController::class);
    Route::resource('events', EventController::class);
    Route::resource('forms', FormsController::class);
});

app/Models/Establishment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Establishment extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'address',
        'owner_name',
        'phone',
        'email',
        'user_id'
    ];

    public function certification()
    {
        return $this->hasOne(Certification::class,'establishment_id','id');
    }

    public function cert($id)
    {
        return Certification::where([
            ['form_id','=',$id],
            ['establishment_id','=',$this->id]
        ])->latest('created_at')->first();
    }
}

app/Http/Controllers/EstablishmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Establishment;
use App\Models\Event;
use App\Models\Form;
use Auth;
use DB;

class EstablishmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('auth');
        $this->middleware('permission:establishment-list|establishment-create|establishment-edit|establishment-delete', ['only' => ['index','show']]);
        $this->middleware('permission:establishment-create', ['only' => ['create','store']]);
        $this->middleware('permission:establishment-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:establishment-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = Auth::user();

        $keyword = $request->input('s');

        $where = array();

        $establishments = Establishment::orderBy('created_at', 'desc');

        if ( $keyword ) {

            $establishments = $establishments->where('name','like','%'.$keyword.'%')
                ->orWhere('owner_name','like','%'.$keyword.'%');
        }

        if ( $user->hasRole('Client') ) {
            
            $establishments = $establishments->where('user_id','=',$user->id);
        }

        $establishments = $establishments->paginate(10);
        $events = Event::latest()->paginate(5);

        return view('establishments.index',compact('establishments','keyword','events'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('establishments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
            'description' => 'required',
            'address' => 'required',
            'owner_name' => 'required',
            'phone' => 'required'
        ]);

        $user = Auth::user();
        $data = $request->all();
        $data['user_id'] = $user->id;

        Establishment::create($data);
    
        return redirect()->route('establishments.index')
                        ->with('success','Certification created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Establishment $establishment)
    {
        $forms = Form::all();

        $status = array(
            'pending' => 'orange',
            'approved' => 'cyan',
            'expired' => 'plum',
        );

        $message = array(
            'pending' => 'Your permit is currently being reviewed.',
            'approved' => 'Your permit is approved!',
            'expired' => 'Your permit has expired.',
        );

        return view('establishments.show',compact('establishment','forms','status','message'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Establishment $establishment)
    {

        $user = Auth::user();

        if (!$user->hasRole('Admin')) {
            
            $arr = [
                'id' => $user->id,
                'user_id' => $establishment->user_id
            ];

            // dd($arr);

            if ($user->id != $establishment->user_id) {

                return redirect('establishments');
            }
        }

        return view('establishments.edit',compact('establishment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Establishment $establishment)
    {
        request()->validate([
            'name' => 'required',
            'description' => 'required',
            'address' => 'required',
            'owner_name' => 'required',
            'phone' => 'required'
        ]);

        $user = Auth::user();

        if (!$user->hasRole('Admin')) {
            if ($user->id != $establishment->user_id) {
                return redirect()->route('establishments.index')
                    ->with('error','Please try again.');
            }
        }

        $establishment->update($request->all());

        return redirect()->route('establishments.index')
                        ->with('success','Establishment updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/establishments/create.blade.php
@extends('neon')


@section('title')
<h2>Establishments</h2>
@endsection

@section('action')
    <a href="javascript:;" onclick="window.history.back();" class="btn btn-primary">
        Go Back 
    </a>
@endsection

@section('content')
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        <br>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br>
    @endif

    <form action="{{ route('establishments.store') }}" method="POST">
        @csrf
        <div class="panel panel-default panel-shadow" data-collapsed="0"><!-- to apply shadow add class "panel-shadow" -->
                    
            <div class="panel-heading">
                <div class="panel-title">Create Establishment</div>
            </div>
            
            <div class="panel-body">
                
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name1">Name of Establishment</label>
                            <input type="text" name="name" class="form-control" id="name1" placeholder="" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="nature-of-business">Nature of Business</label>
                            <input type="text" name="description" class="form-control" id="nature-of-business" placeholder="">
                        </div>  
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="inputAddress">Address</label>
                            <input type="text" name="address" class="form-control" id="inputAddress" placeholder="" required>
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="owner-name">Owner Name</label>
                            <input type="text" name="owner_name" class="form-control" id="owner-name" placeholder="" required>
                        </div>  
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="" required>
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" name="email" class="form-control" id="email" placeholder="">
                        </div>  
                    </div>
                </div>
                
                <button type="submit" class="btn btn-primary btn-icon">Register <i class="entypo-check"></i></button>  
            </div>
            
        </div>
    </form>
@endsection

resources/views/establishments/edit.blade.php
@extends('neon')


@section('title')
<h2>Edit Establishment</h2>
@endsection

@section('action')
    <a href="javascript:;" onclick="window.history.back();" class="btn btn-primary btn-icon icon-left">
        Go Back <i class="entypo-left-open"></i>
    </a>
@endsection

@section('content')
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        <br>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br>
    @endif

    <form action="{{ route('establishments.update',$establishment->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="panel panel-default panel-shadow" data-collapsed="0"><!-- to apply shadow add class "panel-shadow" -->
                    
            <div class="panel-heading">
                <div class="panel-title">Create Establishment</div>
            </div>
            
            <div class="panel-body">
                
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name1">Name of Establishment</label>
                            <input type="text" name="name" class="form-control" id="name1" value="{{ $establishment->name }}" placeholder="" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="nature-of-business">Nature of Business</label>
                            <input type="text" name="description" class="form-control" value="{{ $establishment->description }}" id="nature-of-business" placeholder="">
                        </div>  
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="inputAddress">Address</label>
                            <input type="text" name="address" class="form-control" value="{{ $establishment->address }}"id="inputAddress" placeholder="" required>
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="owner-name">Owner Name</label>
                            <input type="text" name="owner_name" class="form-control" value="{{ $establishment->owner_name }}" id="owner-name" placeholder="" required>
                        </div>  
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="text" name="phone" class="form-control" value="{{ $establishment->phone }}" id="phone" placeholder="" required>
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" name="email" class="form-control" value="{{ $establishment->email }}" id="email" placeholder="">
                        </div>  
                    </div>
                </div>
                
                <button type="submit" class="btn btn-primary btn-icon">Update <i class="entypo-check"></i></button>  
            </div>
            
        </div>
    </form>
@endsection

resources/views/establishments/index.blade.php
@extends('neon')


@section('title')
<h2>Establishments</h2>
@endsection

@section('action')
    {{-- @can('establishment-create')
        <a href="{{ route('establishments.create') }}" class="btn btn-primary btn-icon">
            Register Establishement <i class="entypo-plus"></i>
        </a>
    @endcan --}}
@endsection

@section('content')
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        <br>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br>
    @endif

    <div class="row">
        
        <div class="col-md-9">
            <div class="panel panel-default panel-shadow" data-collapsed="0"><!-- to apply shadow add class "panel-shadow" -->
                <div class="panel-heading">
                    <div class="panel-title">Establishments</div>
                </div>
                
                <div class="panel-body">
                    
                    <div class="row">
                        <div class="col-md-3">

                            <form action="{{ route('establishments.index') }}" method="GET">
                                <div class="input-group">
                                    <input type="text" name="s" value="{{ $keyword }}" class="form-control" placeholder="Search...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="submit">
                                            <i class="entypo-search"></i>
                                        </button>
                                    </span>
                                </div>

                            </form>
                        </div>
                        <div class="col-md-9">
                            @can('establishment-create')
                            <a href="{{ route('establishments.create') }}" class="btn btn-primary btn-icon pull-right">
                                Register Establishement <i class="entypo-plus"></i>
                            </a>
                            @endcan
                        </div><!-- comment -->
                    </div>
                    
                    <hr>

                    @if( $establishments->count() )

                        <table class="table table-hover">
                            <tr>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Owner</th>
                                <th>Phone</th>
                                <th width="280px" class="text-right">Action</th>
                            </tr>
                            @foreach ($establishments as $establishment)
                            <tr>
                                <td>
                                    <a class="btn btn-link btn-xs" href="{{ route('establishments.show',$establishment->id) }}">
                                        {{ $establishment->name }}
                                    </a>
                                </td>
                                <td>{{ $establishment->address }}</td>
                                <td>{{ $establishment->owner_name }}</td>
                                <td>{{ $establishment->phone }}</td>
                                <td>
                                    
                                    <a class="btn btn-info btn-xs btn-icon" href="{{ route('establishments.show',$establishment->id) }}">View Certifications <i class="entypo-eye"></i></a>
                                    @can('establishment-edit')
                                    <a class="btn btn-primary btn-xs btn-icon" href="{{ route('establishments.edit',$establishment->id) }}">Edit <i class="entypo-pencil"></i></a>
                                    @endcan
                                    @can('establishment-delete')
                                    <a href="javascript:;" onclick="jQuery('#modal-{{$establishment->id}}').modal('show');" class="btn btn-danger btn-xs btn-icon">Delete <i class="entypo-cancel"></i></a>
                                    @endcan
                                
                                    <div class="modal fade" id="modal-{{$establishment->id}}">
                                        <div class="modal-dialog">
                                            <form action="{{ route('establishments.destroy',$establishment->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <div class="modal-content">
                                                    
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                        <h4 class="modal-title">Delete</h4>
                                                    </div>
                                                    
                                                    <div class="modal-body">
                                                        Are you sure you wish to delete the establishment <b>{{ $establishment->name }}</b> owned by by <b>{{ $establishment->owner_name }}</b>? 
                                                    </div>
                                                    
                                                    <div class="modal-footer">
                                                        <a href="javascript:;" class="btn btn-default" data-dismiss="modal">Cancel</a>
                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </table>

                        {!! $establishments->links() !!}
                        
                    @else 

                        <div class="alert alert-info alert-dismissible show" role="alert">
                            @if($keyword)
                            <p>No results found.</p>
                            @else
                            <p>
                                You do not have any establishments registered at the moment. <br>
                                You may now start adding here: </p><br><a href="{{ route('establishments.create') }}" class="btn btn-primary btn-icon">
                                Register Your Establishement <i class="entypo-plus"></i>
                            </a>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            @endif
                        </div>

                    @endif
                    
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="panel panel-default panel-shadow" data-collapsed="0"><!-- to apply shadow add class "panel-shadow" -->
                <div class="panel-heading">
                    <div class="panel-title">Upcoming Events</div>
                </div>
                <div class="panel-body">

                    @if( $events->count() )
                       
                        @foreach ($events as $event)

                            <div class="tile-stats tile-white-gray">
                                <div class="icon"><i class="entypo-calendar"></i></div>
                                <div class="num">{{ $event->name }}</div>
                                <h3>{{ $event->description }}</h3>
                                <p>{{ date('F d, Y', strtotime($event->start_date)) }}</p>
                            </div>
                                
                        @endforeach

                        {!! $events->links() !!}

                    @else 
                        <div class="alert alert-info" role="alert">
                          There are no events to display at the moment.
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    

    

    

    

    

@endsection

resources/views/establishments/show.blade.php
@extends('neon')

@section('title')
<h2>{{ $establishment->name }}</h2>
@endsection

@section('action')
    <a class="btn btn-primary icon-left btn-icon" href="{{ route('establishments.index') }}">
        Go Back <i class="entypo-left-open"></i>
    </a>
@endsection

@section('content')

<br>
<div class="panel panel-default panel-shadow" data-collapsed="0"><!-- to apply shadow add class "panel-shadow" -->

    <!-- panel head -->
    <div class="panel-heading">
        <div class="panel-title">Certifications</div>
    </div>

    <!-- panel body -->
    <div class="panel-body">

        <?php 
        $numOfCols = 4;
        $rowCount = 0;
        $bootstrapColWidth = 12 / $numOfCols;

        ?>
       <div class="row">

            @foreach( $forms as $form )
                <?php $cert = $establishment->cert($form->id); ?>
                <div class="col-sm-3">
                    <div class="tile-stats tile-{{ ($cert) ? $status[$cert->status]:'gray' }}">
                        <div class="icon"><i class="entypo-newspaper"></i></div>
                        
                        @if($cert)
                            <h3>{{ $form->name }}</h3>
                            <p>{{ $message[$cert->status] }}</p><br>
                            @if($cert->status=='expired')
                                <a class="btn btn-xs btn-danger btn-icon" href="{{ route('forms.show', $form->id) }}?es={{ $establishment->id }}">Request Renewal <i class="entypo-right-open"></i></a>
                            @endif
                            @if($cert->status=='pending')
                                <a class="btn btn-xs btn-default btn-icon" href="{{ route('certifications.show',$cert->id) }}">View details <i class="entypo-right-open"></i></a>
                            @endif
                            @if($cert->status=='approved')

                                <a class="btn btn-xs btn-default btn-icon" href="{{ route('certifications.show',$cert->id) }}?print=1" target="_blank">Print Permit<i class="entypo-print"></i></a>
                                @if($cert->valid_until)
                                <span class="btn btn-xs btn-link" style="color:#fff;">
                                Valid Until: <b>{{ \Illuminate\Support\Carbon::parse($cert->valid_until)->format('F j, Y') }}</b>
                                </span>
                                @endif
                            @endif
                        @else
                            <h4>{{ $form->name }}</h4><br>
                            <a href="{{ route('forms.show', $form->id) }}?es={{ $establishment->id }}" class="btn btn-info">Get Certification</a>
                        @endif
                    </div>
                </div>
                <?php 
                $rowCount++;
                if($rowCount % $numOfCols == 0) echo '</div><div class="row">'; ?>
            @endforeach
            
        </div>

    </div>

</div>

@endsection