routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PublicController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CertificationController;
use App\Http\Controllers\EstablishmentController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\FormsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PublicController::class,'index'])->name('public');
Route::post('/sendmail', [PublicController::class,'sendmail'])->name('sendmail');
Route::get('/cron', [PublicController::class,'cron'])->name('cron');

Route::get('/dashboard', function () {
    return view('neon');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/settings', [HomeController::class, 'settings'])->name('settings');
Route::patch('/settings/update', [HomeController::class, 'settings_update'])->name('settings_update');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('certifications', CertificationController::class);
    Route::resource('establishments', EstablishmentController::class);
    Route::resource('events', EventController::class);
    Route::resource('forms', FormsController::class);
});

app/Models/Certification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Certification extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *	
     * @var array
     */
    protected $fillable = [
        'name', // name fo the form
        'contents', 
        'valid_from',
        'valid_until',
        'status',
        'user_id',
        'form_id',
        'establishment_id'
    ];

    public function user()
    {
        return $this->hasOne(User::class,'id','user_id');
    }

    public function form()
    {
        return $this->hasOne(Form::class,'id','form_id');
    }

    public function establishment()
    {
        return $this->hasOne(Establishment::class,'id','establishment_id');
    }
}

app/Http/Controllers/CertificationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Certification;
use App\Models\Establishment;
use Illuminate\Support\Str;
use App\Models\Form;
use Illuminate\Support\Carbon;
use Auth;

class CertificationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('auth');
        $this->middleware('permission:certification-list|certification-create|certification-edit|certification-delete', ['only' => ['index','show']]);
        $this->middleware('permission:certification-create', ['only' => ['create','store']]);
        $this->middleware('permission:certification-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:certification-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $status = array(
            'pending' => 'warning',
            'approved' => 'success',
            'expired' => 'danger'
        );

        $user = Auth::user();

        $keyword = $request->input('s');

        $where = array();

        $certifications = Certification::orderBy('created_at', 'desc');

        if ( $keyword ) {

            $certifications = $certifications->where('name','like','%'.$keyword.'%')
                ->orWhereHas('user', function($q) use ($keyword) {
                    return $q->where('name', 'LIKE', '%' . $keyword . '%');
                });
        }

        if ( $user->hasRole('Customer') ) {
            
            $certifications = $certifications->where('user_id','=',$user->id);
        }

        $certifications = $certifications->paginate(10);

        return view('certifications.index',compact('certifications','status','keyword'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        // $form = $request->input('form');
        // $id = $request->input('id');
        // $view = '';

        // $form = Form::find($form);
        // if ($form) { $view = $form->view; }

        // if ( empty($view) ) {
        //     return redirect('establishments/'.$id);
        // }

        // return view($view);
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = [
            'name' => 'required',
            'form_id' => 'integer|required',
            'establishment_id' => 'integer|required',
            'contents' => 'required'
        ];

        $data = $request->all();
        $user = Auth::user();

        if ( $user->hasRole('Admin') || $user->hasRole('Employee') ) 
        {
            $valid_from = Carbon::parse($data['valid_from'])->format('Y-m-d');
            $valid_until = Carbon::parse($data['valid_until'])->format('Y-m-d');

            $validate['valid_from'] = 'required|date';
            $validate['valid_until'] = 'required|date|after:valid_from';

            $data['valid_from'] = $valid_from;
            $data['valid_until'] = $valid_until;

            if ( $request->input('status') ) {
                $data['status'] = $request->input('status');
            }
        }

        request()->validate($validate);
        
        $data['contents'] = json_encode($request->input('contents'));
        $data['user_id'] = $user->id;

        Certification::create($data);

        $establishment = Establishment::find($request->input('establishment_id'));
        $form = Form::find($request->input('form_id'));

        if ( $establishment && $form )
        {
            $message = 'Hi '.$establishment->owner_name.', we recieved your permit request for '. $form->name . '. ';
            $message .= 'Kindly settle your payment in our office before '. date('F d, Y', strtotime('+4 days'));
            $this->sendSMS($establishment->phone, $message);
        }
        
        return redirect()->route('establishments.show', $request->input('establishment_id'))
                        ->with('success','Certification created successfully.');
    }
    
    /**
     * Display the specified resource.
     *
     * @param  \App\Certification  $certification
     * @return \Illuminate\Http\Response
     */
    public function show(Certification $certification, Request $request)
    {
        $data = json_decode($certification->contents);

        if ($request->input('print')) {
            
            return view('certifications.print',compact('certification','data'));

        } else {

            return view('forms.show',compact('certification','data'));
        }
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Certification  $certification
     * @return \Illuminate\Http\Response
     */
    public function edit(Certification $certification)
    {
        $data = json_decode($certification->contents);
        $establishment = $certification->establishment;
        $form = $certification->form;

        if (!$establishment) {
            return redirect('establishments');
        }

        $right = null;
        $left = null;
        $fields = null;

        if ( $form->fields ) 
        {
            $fields = json_decode($form->fields);

            $right = $fields->right;
            $left = $fields->left;

            if (count($left)) 
            {   
                $newLeft = [];
                foreach ( $left as $l ) 
                {
                    $l = json_decode($l);
                    $l->slug = Str::slug($l->name, '_');
                    $newLeft[] = $l;
                }

                $left = $newLeft;
            }   

            if (count($right)) 
            {

                $newRight = [];
                foreach ( $right as $r ) 
                {
                    $r = json_decode($r);
                    $r->slug = Str::slug($r->name, '_');
                    $newRight[] = $r;
                }

                $right = $newRight;
            }
        }

        // dd($data);
        $arr = [];
        foreach ($data as $key => $val) {
            $arr[$key] = $val;
        }

        $data = $arr;

        return view('certifications.edit',compact('certification','data','form','establishment','left','right','fields'));
    
        // return view($view,compact('certification','data','establishment','form'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Certification  $certification
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Certification $certification)
    {
        $validate = [
            'name' => 'required',
            'form_id' => 'integer|required',
            'establishment_id' => 'integer|required',
            'contents' => 'required'
        ];

        $data = $request->all();
        $user = Auth::user();

        if ($user->hasRole('Admin') || $user->hasRole('Employee')) 
        {
            $valid_from = Carbon::parse($data['valid_from'])->format('Y-m-d');
            $valid_until = Carbon::parse($data['valid_until'])->format('Y-m-d');

            $validate['valid_from'] = 'required|date';
            $validate['valid_until'] = 'required|date|after:valid_from';

            $data['valid_from'] = $valid_from;
            $data['valid_until'] = $valid_until;

            if ( $request->input('status') ) {
                $data['status'] = $request->input('status');
            }
        }

        request()->validate($validate);
        
        $data['contents'] = json_encode($request->input('contents'));

        $certification->update($data);

        $establishment = Establishment::find($request->input('establishment_id'));
        $form = Form::find($request->input('form_id'));

        if ( $establishment && $form )
        {
            $message = '';

            if ($request->input('status') == 'approved') 
            {
                $message = 'Hi '.$establishment->owner_name.', your permit request for '. $form->name;
                $message .= ' has been approved and will expire on '. Carbon::parse($data['valid_until'])->format('F d, Y');
            }

            if ($request->input('status') == 'expired') 
            {
                $message = 'Hi '.$establishment->owner_name.', your permit '. $form->name;
                $message .= ' has expired. Kindly request a new permit for '.$establishment->name;
            }

            if ( !empty($message) ) 
            {
                $this->sendSMS($establishment->phone, $message);   
            }
        }
    
        return redirect()->route('certifications.index')
                        ->with('success','Certification updated successfully');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Certification  $certification
     * @return \Illuminate\Http\Response
     */
    public function destroy(Certification $certification)
    {
        $certification->delete();
    
        return redirect()->route('certifications.index')
                        ->with('success','Certification deleted successfully');
    }

    public function sendSMS($phone,$message)
    {
        $args = [
          'phone' => $phone,
          'message' => $message,
          'code' => 'bfpj'
        ];

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,"https://sms.iloiloshop.com");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($args) );

resources/views/certifications/create.blade.php
@extends('neon')

@section('title')
<h2>Register New Certification</h2>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            
            <a class="btn btn-default" href="javascript:;" onclick="window.history.back();"> Back</a>
            
        </div>
    </div>

    <hr>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('certifications.store') }}" method="POST">
    	@csrf
         <div class="row">
		    <div class="col-xs-12 col-sm-6 col-md-6">
		        <div class="form-group">
		            <strong>Name of Establishment:</strong>
		            <input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="">
		        </div>
                <div class="form-group">
                    <strong>Name of Owner/Representative:</strong>
                    <input type="text" name="owner_name" value="{{ old('owner_name') }}" class="form-control" placeholder="">
                </div>
                <div class="form-group">
                    <strong>Purpose:</strong>
                    <select name="purpose" class="form-control">
                        <option value="For Business Permit (NEW/RENEWAL)">For business permit (NEW/RENEWAL)</option>
                        <option value="Certificate of Annual Inspection (PEZA)">Certificate of Annual Inspection (PEZA)</option>
                    </select>
                </div>
                <div class="form-group">
                    <strong>Address:</strong>
                    <input type="text" name="address" value="{{ old('address') }}" class="form-control" placeholder="Janiuay Public Market, Janiuay, Iloilo City">
                </div>
                <div class="form-group">
                    <strong>FSIC Number:</strong>
                    <input type="text" name="fsic_number" value="{{ old('fsic_number') }}" class="form-control" placeholder="FSIC Number">
                </div>
		    </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                @can('certification-delete')
                <div class="form-group">
                    <strong>Status:</strong>
                    <select name="status" class="form-control">
                        <option value="pending">Pending</option>
                        <option value="approved">Approved</option>
                        <option value="expired">Expired</option>
                    </select>
                </div>
                @endcan
                <div class="form-group">
                    <strong>Amount Paid:</strong>
                    <input type="text" name="amount_paid" value="{{ old('amount_paid') }}" class="form-control" placeholder="0.00">
                </div>
                <div class="form-group">
                    <strong>Reciept Number:</strong>
                    <input type="text" name="reciept_number" value="{{ old('reciept_number') }}" class="form-control" placeholder="">
                </div>
                <div class="form-group">
                    <strong>Payment Date:</strong>
                    <input type="text" name="date_paid" value="{{ old('date_paid') }}" class="form-control" placeholder="MM/DD/YYYY">
                </div>
                @can('certification-delete')
                <div class="form-group">
                    <strong>Valid Until:</strong>
                    <input type="text" name="valid_until" value="{{ old('valid_until') }}" class="form-control" placeholder="MM/DD/YYYY">
                </div>
                @endcan
            </div>
            
		    <div class="col-xs-12 col-sm-12 col-md-12">
                <button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>


    </form>

@endsection

resources/views/certifications/index.blade.php
@extends('neon')


@section('title')
<h2>Submitted Permit</h2>
@endsection

@section('action')
    
@endsection

@section('content')

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <br>
    <div class="panel panel-default panel-shadow" data-collapsed="0"><!-- to apply shadow add class "panel-shadow" -->
                    
        <!-- panel head -->
        <div class="panel-heading">
            <div class="panel-title">Submitted Forms</div>
        </div>
        
        <!-- panel body -->
        <div class="panel-body">
            
            <div class="row">
                <div class="col-md-3">

                    <form action="{{ route('certifications.index') }}" method="GET">
                        <div class="input-group">
                            <input type="text" name="s" value="{{ $keyword }}" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="submit">
                                    <i class="entypo-search"></i>
                                </button>
                            </span>
                        </div>

                    </form>
                </div>
            </div>

            <hr>

            <div class="card">
                <div class="card-body">

                    @if( $certifications->count() )

                    <table class="table table-hover">
                        <tr>
                            <th>Status</th>
                            <th>Form</th>
                            <th>Customer</th>
                            <th>Valid From</th>
                            <th>Valid Until</th>
                            <th width="280px" class="text-right">Action</th>
                        </tr>
                        @foreach ($certifications as $certification)
                        <tr>
                            <td>
                                <span style="border-radius:50%;" class="btn btn-xs btn-{{ $status[$certification->status] }}">
                                    <b class="entypo-record"></b>
                                <span>
                            </td>
                            <td>
                                <a class="btn btn-link btn-xs" href="{{ route('certifications.show',$certification->id) }}">
                                    {{ $certification->name }}
                                </a>
                            </td>
                            <td>{{ $certification->user->name }}</td>
                            <td>
                                @if($certification->valid_from)
                                {{ \Illuminate\Support\Carbon::parse($certification->valid_from)->format('F j, Y') }}
                                @endif
                            </td>
                            <td>
                                @if($certification->valid_until)
                                {{ \Illuminate\Support\Carbon::parse($certification->valid_until)->format('F j, Y') }}
                                @endif
                            </td>
                            <td>
                                <div class="pull-right">
                                    @if($certification->status == 'expired')
                                        <a class="btn btn-info btn-xs btn-icon" href="{{ route('certifications.show',$certification->id) }}">View <i class="entypo-eye"></i></a>
                                    @endif
                                    @if($certification->status == 'approved')
                                        <a class="btn btn-xs btn-success btn-icon" target="_blank" href="{{ route('certifications.show',$certification->id) }}?print=1">Print<i class="entypo-print"></i></a>
                                    @endif
                                    @can('certification-edit')
                                        <a class="btn btn-primary btn-xs btn-icon{{ $certification->status == 'expired' ? ' disabled':'' }}" href="{{ route('certifications.edit',$certification->id) }}"{{ $certification->status == 'expired' ? ' disabled':'' }}>Edit <i class="entypo-pencil"></i></a>
                                    @endcan
                                    @can('certification-delete')
                                        <a href="javascript:;" onclick="jQuery('#modal-{{$certification->id}}').modal('show');" class="btn btn-danger btn-xs btn-icon">Delete <i class="entypo-cancel"></i></a>
                                    @endcan
                                </div>
                                <div class="modal fade" id="modal-{{$certification->id}}">
                                    <div class="modal-dialog">
                                        <form action="{{ route('certifications.destroy',$certification->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <div class="modal-content">
                                                
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                    <h4 class="modal-title">Delete</h4>
                                                </div>
                                                
                                                <div class="modal-body">
                                                    Are you sure you wish to delete the form <b>{{ $certification->name }}</b> submitted by <b>{{ $certification->user->name }}</b>? 
                                                </div>
                                                
                                                <div class="modal-footer">
                                                    <a href="javascript:;" class="btn btn-default" data-dismiss="modal">Cancel</a>
                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </table>

                    {!! $certifications->links() !!}

                    @else 

                    <div class="alert alert-info alert-dismissible show" role="alert">
                        @if($keyword)
                        <p>No results found.</p>
                        @else
                        <p>There are no available data to show at the moment.</p>
                        @endif
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>

                    </div>

                    @endif

                </div>
            </div>
        </div>
        
    </div>

   
    


    

@endsection

resources/views/certifications/print.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Print</title>
        <style>
            table{border:1px solid #ccc;}
            table th{padding: 5px 10px;border:1px solid #ccc;background: #e8e8e8;text-align: left;}
            table td{padding: 5px 10px;border:1px solid #ccc;}
        </style>
    </head>
    <body>
        <div align="center">
            <h3>{{ $certification->name }}</h3>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach( $data as $key => $val )

                        @if( $key != '_token' )
                        <tr>
                            <td>{{ ucwords( str_replace('_', ' ', $key) ) }}</td>
                            <td>{{ $val }}</td>
                        </tr>
                        @endif

                    @endforeach
                    @if($certification->status!='pending')
                    <tr>
                        <td>Valid From</td>
                        <td>{{ \Illuminate\Support\Carbon::parse($certification->valid_from)->format('F j, Y') }}</td>
                    </tr>
                    <tr>
                        <td>Valid Until</td>
                        <td>{{ \Illuminate\Support\Carbon::parse($certification->valid_until)->format('F j, Y') }}</td>
                    </tr> 
                    @endif
                </tbody>
            </table>
        </div>
        <script>window.print();</script>
    </body>
</html>

resources/views/certifications/show.blade.php
@extends('neon')

@section('title')
<h2>Certification Details</h2>
@endsection

@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <a class="btn btn-default" href="javascript:;" onclick="window.history.back();"> Back</a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name of Establishment:</strong>
                {{ $certification->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name of Owner/Representative:</strong>
                {{ $certification->owner_name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Address:</strong>
                {{ $certification->address }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>FSIC Number:</strong>
                {{ $certification->fsic_number }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Purpose:</strong>
                {{ $certification->purpose }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Amount Paid:</strong>
                {{ $certification->amount_paid }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Payment Date:</strong>
                {{ $certification->date_paid }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Valid Until:</strong>
                {{ $certification->valid_until }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Status:</strong>
                {{ $certification->status }}
            </div>
        </div>
    </div>

@endsection